# doc-warnings: true
# test-warnings: false
strictness: medium
pep8:
  full: true
  disable:
    - E1004
pylint:
  disable:
    # - dangerous-default-value
    # - missing-super-argument
    # - super-on-old-class
    # - protected-access
    # - old-style-class
max-line-length: 120
uses:
  - django
  - celery
# autodetect: yes
requirements:
  - django/requirements.txt

ignore-patterns:
  - /migrations/
  - /watson/

python-targets:
  - 3
