# overrides for production
version: '2.1'
services:
  webpack:
    command: "true"
    volumes:
      - ./build:/app/build/

  web:
    command: "uwsgi"
    environment:
      - DEBUG=False
    volumes:
      - ./build:/app/build/
