#!/bin/bash
# Build and demonize docker container
case $1 in
  build )
    echo "building"
    COMPOSE_FILE=docker-compose.yml:docker-compose.production.yml
    docker-compose build
    docker-compose run --rm webpack build 
    docker-compose run --rm web django-admin migrate
    docker-compose run --rm web django-admin collectstatic --noinput
    ;;
  production )
    echo "running universitas production"
    COMPOSE_FILE=docker-compose.yml:docker-compose.production.yml
    docker-compose down
    ;;
  development )
    echo "running universitas development"
    unset COMPOSE_FILE
    docker-compose down
    ;;
  * ) 
    echo "usage $0 build | $0 production | $0 development"
    exit 1
    ;;
esac
docker-compose up -d
docker ps
